# Generated by Django 4.2.11 on 2024-03-11 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitems', to='Jewelry.maincategory'),
        ),
    ]
