# Generated by Django 4.2.11 on 2024-03-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewelry', '0006_alter_shippingaddress_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('delivery', 'Delivery')], max_length=20, null=True),
        ),
    ]
