# Generated by Django 4.2.11 on 2024-03-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewelry', '0008_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_ordered_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
