# Generated by Django 4.2.11 on 2024-03-11 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('created_time', models.TimeField(default=django.utils.timezone.now)),
                ('author_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('phoneno1', models.CharField(max_length=15)),
                ('phoneno2', models.CharField(blank=True, max_length=15, null=True)),
                ('emailno1', models.EmailField(max_length=254)),
                ('emailno2', models.EmailField(blank=True, max_length=254, null=True)),
                ('store_location', models.CharField(max_length=255)),
                ('copywrite_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('title_no1', models.CharField(max_length=255, null=True)),
                ('title_no2', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
